version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: yeepay-backend
    ports:
      - "9001:9000"
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=9000
      - COMFYUI_URL=http://host.docker.internal:8188
      - COMFYUI_OUTPUT_DIR=/app/comfyui/output/yeepay
      - COMFYUI_MAIN_OUTPUT_DIR=/app/comfyui/output
      - COMFYUI_INPUT_DIR=/app/comfyui/input
      - COMFYUI_TIMEOUT=300
      - MAX_CONCURRENT_TASKS=3
      - CORS_ORIGINS=*
      - DEBUG=false
      - LOG_LEVEL=INFO
      - OLLAMA_URL=http://host.docker.internal:11434
    networks:
      - yeepay-network
    volumes:
      - yeepay-uploads:/app/uploads
      - yeepay-outputs:/app/outputs
      - yeepay-database:/app/data
      - E:/AI-Image/ComfyUI-aki-v1.4/output:/app/comfyui/output
      - E:/AI-Image/ComfyUI-aki-v1.4/output/yeepay:/app/comfyui/output/yeepay
      - E:/AI-Image/ComfyUI-aki-v1.4/input:/app/comfyui/input
      - E:/AI-Image/ComfyUI-aki-v1.4/models/loras:/app/comfyui/models/loras
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yeepay-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - yeepay-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  yeepay-network:
    driver: bridge

volumes:
  yeepay-uploads:
  yeepay-outputs:
  yeepay-database: 