version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: yeepay-backend
    ports:
      - "9001:9000"

    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=9000
      - COMFYUI_URL=http://host.docker.internal:8188
      - COMFYUI_OUTPUT_DIR=/app/comfyui/output/yeepay
      - COMFYUI_MAIN_OUTPUT_DIR=/app/comfyui/output
      - COMFYUI_INPUT_DIR=/app/comfyui/input
      - COMFYUI_TIMEOUT=300
      - MAX_CONCURRENT_TASKS=3
      - CORS_ORIGINS=*
      - DEBUG=false
      - LOG_LEVEL=INFO
      - OLLAMA_URL=http://host.docker.internal:11434
    networks:
      - yeepay-network
    volumes:
      - yeepay-uploads:/app/uploads
      - yeepay-outputs:/app/outputs
      - yeepay-database:/app/data
      - D:/AI-Image/ComfyUI-aki-v1.6/ComfyUI/output:/app/comfyui/output
      - D:/AI-Image/ComfyUI-aki-v1.6/ComfyUI/output/yeepay:/app/comfyui/output/yeepay
      - D:/AI-Image/ComfyUI-aki-v1.6/ComfyUI/input:/app/comfyui/input

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



  # 统一Web服务（前端+nginx）
  web:
    image: nginx:alpine
    container_name: yeepay-web
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - yeepay-network
    restart: unless-stopped

networks:
  yeepay-network:
    driver: bridge

volumes:
  yeepay-uploads:
  yeepay-outputs:
  yeepay-database: 