version: '3.8'

services:
  # 后端API服务（开发环境）
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: yeepay-backend-dev
    ports:
      - "9000:9000"

    environment:
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=9000
      - COMFYUI_URL=http://host.docker.internal:8188
      - COMFYUI_OUTPUT_DIR=/app/comfyui/output/yeepay
      - COMFYUI_TIMEOUT=300
      - MAX_CONCURRENT_TASKS=3
      - CORS_ORIGINS=*
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - OLLAMA_URL=http://host.docker.internal:11434
    networks:
      - yeepay-dev-network
    volumes:
      - yeepay-dev-uploads:/app/uploads
      - yeepay-dev-outputs:/app/outputs
      - yeepay-dev-database:/app/tasks.db
      - D:/AI-Image/ComfyUI-aki-v1.6/ComfyUI/output:/app/comfyui/output
      - D:/AI-Image/ComfyUI-aki-v1.6/ComfyUI/output/yeepay:/app/comfyui/output/yeepay
      - D:/AI-Image/ComfyUI-aki-v1.6/ComfyUI/input:/app/comfyui/input

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  yeepay-dev-network:
    driver: bridge

volumes:
  yeepay-dev-uploads:
  yeepay-dev-outputs:
  yeepay-dev-database:
