"""Add unet, clip, and vae paths to base model

Revision ID: fa3601714028
Revises: 75bb56ca1a07
Create Date: 2025-09-12 20:31:07.808827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3601714028'
down_revision: Union[str, None] = '75bb56ca1a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unet_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('clip_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vae_path', sa.String(length=255), nullable=True))

    op.execute("UPDATE base_models SET unet_path = '', clip_path = '', vae_path = ''")

    with op.batch_alter_table('base_models', schema=None) as batch_op:
        batch_op.alter_column('unet_path', existing_type=sa.String(length=255), nullable=False)
        batch_op.alter_column('clip_path', existing_type=sa.String(length=255), nullable=False)
        batch_op.alter_column('vae_path', existing_type=sa.String(length=255), nullable=False)
        batch_op.drop_column('model_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_models', sa.Column('model_file_path', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('base_models', 'vae_path')
    op.drop_column('base_models', 'clip_path')
    op.drop_column('base_models', 'unet_path')
    # ### end Alembic commands ###
